[package]
name = "rust-wheels"
version = "0.1.0"
authors = ["Mikhail Hogrefe <mikhailhogrefe@gmail.com>"]

[lib]
name = "rust_wheels_lib"
path = "src/lib.rs"

[[bin]]
name = "rust_wheels_main"
path = "src/bin.rs"

[dependencies]

gmp-to-flint-adaptor = { path = "../gmp-to-flint-adaptor" }
itertools = "0.5.9"
rand = "0.3.0"
sha3 = "0.4.1"
